# Generated by Django 3.1.7 on 2021-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_article_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='CoverPhoto',
            field=models.ImageField(default='images/5.jpg', upload_to='images/', verbose_name='Cover Picture'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='CoverPhoto',
            field=models.ImageField(default='images/logo1.png', upload_to='images/', verbose_name='Cover Picture'),
        ),
    ]
