# Generated by Django 3.1.7 on 2021-03-15 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20210315_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='UploadDate',
            field=models.DateField(default=datetime.date(2021, 3, 15)),
        ),
    ]
