# Generated by Django 3.1.7 on 2021-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_article_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Description',
            field=models.TextField(default='Description...'),
        ),
    ]
