# Generated by Django 3.1.7 on 2021-03-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='HighlightText',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
