# Generated by Django 3.1.7 on 2021-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_article_highlighttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='CoverPhoto',
            field=models.ImageField(default='images/blog-2.png', upload_to='images/', verbose_name='Cover Picture'),
        ),
    ]
